In [1]:
from bs4 import BeautifulSoup
import requests

import pandas as pd
import numpy as np

In [2]:
url = 'https://en.wikipedia.org/wiki/Historical_mortality_rates_of_puerperal_fever#Yearly_mortality_rates_for_birthgiving_women_1833.E2.80.931858_for_first_and_second_clinics'
r  = requests.get(url)
data = r.text
soup = BeautifulSoup(data, 'html.parser')

In [3]:
print(soup.prettify())

<!DOCTYPE html>
<html class="client-nojs" dir="ltr" lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   Historical mortality rates of puerperal fever - Wikipedia
  </title>
  <script>
   document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );
  </script>
  <script>
   (window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Historical_mortality_rates_of_puerperal_fever","wgTitle":"Historical mortality rates of puerperal fever","wgCurRevisionId":807938268,"wgRevisionId":807938268,"wgArticleId":16951645,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["All articles with unsourced statements","Articles with unsourced statements from May 2016","History of obstetrics","Medical hygiene","Women in history"],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Historical_mortality_rates_of_puerperal_fever","wgRelevantArticleId":16951645,"wgRequestId":"WhTa5gpAMCUAAGuMTIUAAAAB","wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgFlaggedRevsParams":{"tags":{}},"wgStableRevisionId":null,"wgWikiEditorEnabledModules":{"toolbar":true,"preview":false,"publish":false},"wgBetaFeaturesFeatures":[],"wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsShouldSendModuleToUser":true,"wgPopupsConflictsWithNavPopupGadget":false,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en","usePageImages":true,"usePageDescriptions":true},"wgPreferredVariant":"en","wgMFExpandAllSectionsUserOption":false,"wgMFDisplayWikibaseDescriptions":{"search":true,"nearby":true,"watchlist":true,"tagline":false},"wgRelatedArticles":null,"wgRelatedArticlesUseCirrusSearch":true,"wgRelatedArticlesOnlyUseCirrusSearch":false,"wgULSCurrentAutonym":"English","wgNoticeProject":"wikipedia","wgCentralNoticeCookiesToDelete":[],"wgCentralNoticeCategoriesUsingLegacy":["Fundraising","fundraising"],"wgCategoryTreePageCategoryOptions":"{\"mode\":0,\"hideprefix\":20,\"showcount\":true,\"namespaces\":false}","wgWikibaseItemId":"Q5774313","wgCentralAuthMobileDomain":false,"wgCodeMirrorEnabled":false,"wgVisualEditorToolbarScrollOffset":0,"wgVisualEditorUnsupportedEditParams":["undo","undoafter","veswitched"],"wgEditSubmitButtonLabelPublish":false});mw.loader.state({"ext.gadget.charinsert-styles":"ready","ext.globalCssJs.user.styles":"ready","ext.globalCssJs.site.styles":"ready","site.styles":"ready","noscript":"ready","user.styles":"ready","user":"ready","user.options":"ready","user.tokens":"loading","ext.cite.styles":"ready","wikibase.client.init":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","ext.wikimediaBadges":"ready","mediawiki.legacy.shared":"ready","mediawiki.legacy.commonPrint":"ready","mediawiki.sectionAnchor":"ready","mediawiki.skinning.interface":"ready","skins.vector.styles":"ready","ext.globalCssJs.user":"ready","ext.globalCssJs.site":"ready"});mw.loader.implement("user.tokens@1dqfd7l",function ( $, jQuery, require, module ) {
mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});/*@nomin*/

});mw.loader.load(["ext.cite.a11y","site","mediawiki.page.startup","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","jquery.tablesorter","mediawiki.toc","mediawiki.searchSuggest","ext.gadget.teahouse","ext.gadget.ReferenceTooltips","ext.gadget.watchlist-notice","ext.gadget.DRN-wizard","ext.gadget.charinsert","ext.gadget.refToolbar","ext.gadget.extra-toolbar-buttons","ext.gadget.switcher","ext.centralauth.centralautologin","mmv.head","mmv.bootstrap.autostart","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.visualEditor.targetLoader","ext.eventLogging.subscriber","ext.wikimediaEvents","ext.navigationTiming","ext.uls.eventlogger","ext.uls.init","ext.uls.interface","ext.centralNotice.geoIP","ext.centralNotice.startUp","skins.vector.js"]);});
  </script>
  <link href="/w/load.php?debug=false&amp;lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediaBadges%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.sectionAnchor%7Cmediawiki.skinning.interface%7Cskins.vector.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector" rel="stylesheet"/>
  <script async="" src="/w/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=vector">
  </script>
  <meta content="" name="ResourceLoaderDynamicStyles"/>
  <link href="/w/load.php?debug=false&amp;lang=en&amp;modules=ext.gadget.charinsert-styles&amp;only=styles&amp;skin=vector" rel="stylesheet"/>
  <link href="/w/load.php?debug=false&amp;lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector" rel="stylesheet"/>
  <meta content="MediaWiki 1.31.0-wmf.8" name="generator"/>
  <meta content="origin-when-cross-origin" name="referrer"/>
  <meta content="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/AAKH-1784.jpg/1200px-AAKH-1784.jpg" property="og:image"/>
  <link href="android-app://org.wikipedia/http/en.m.wikipedia.org/wiki/Historical_mortality_rates_of_puerperal_fever" rel="alternate"/>
  <link href="/w/index.php?title=Historical_mortality_rates_of_puerperal_fever&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
  <link href="/w/index.php?title=Historical_mortality_rates_of_puerperal_fever&amp;action=edit" rel="edit" title="Edit this page"/>
  <link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
  <link href="/static/favicon/wikipedia.ico" rel="shortcut icon"/>
  <link href="/w/opensearch_desc.php" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
  <link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
  <link href="//creativecommons.org/licenses/by-sa/3.0/" rel="license"/>
  <link href="https://en.wikipedia.org/wiki/Historical_mortality_rates_of_puerperal_fever" rel="canonical"/>
  <link href="//login.wikimedia.org" rel="dns-prefetch"/>
  <link href="//meta.wikimedia.org" rel="dns-prefetch"/>
  <!--[if lt IE 9]><script src="/w/load.php?debug=false&amp;lang=en&amp;modules=html5shiv&amp;only=scripts&amp;skin=vector&amp;sync=1"></script><![endif]-->
 </head>
 <body class="mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject page-Historical_mortality_rates_of_puerperal_fever rootpage-Historical_mortality_rates_of_puerperal_fever skin-vector action-view">
  <div class="noprint" id="mw-page-base">
  </div>
  <div class="noprint" id="mw-head-base">
  </div>
  <div class="mw-body" id="content" role="main">
   <a id="top">
   </a>
   <div class="mw-body-content" id="siteNotice">
    <!-- CentralNotice -->
   </div>
   <div class="mw-indicators mw-body-content">
   </div>
   <h1 class="firstHeading" id="firstHeading" lang="en">
    Historical mortality rates of puerperal fever
   </h1>
   <div class="mw-body-content" id="bodyContent">
    <div class="noprint" id="siteSub">
     From Wikipedia, the free encyclopedia
    </div>
    <div id="contentSub">
    </div>
    <div class="mw-jump" id="jump-to-nav">
     Jump to:
     <a href="#mw-head">
      navigation
     </a>
     ,
     <a href="#p-search">
      search
     </a>
    </div>
    <div class="mw-content-ltr" dir="ltr" id="mw-content-text" lang="en">
     <div class="mw-parser-output">
      <div class="thumb tright">
       <div class="thumbinner" style="width:302px;">
        <a class="image" href="/wiki/File:AAKH-1784.jpg">
         <img alt="" class="thumbimage" data-file-height="1443" data-file-width="2007" height="216" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/e7/AAKH-1784.jpg/300px-AAKH-1784.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/e7/AAKH-1784.jpg/450px-AAKH-1784.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/e/e7/AAKH-1784.jpg/600px-AAKH-1784.jpg 2x" width="300"/>
        </a>
        <div class="thumbcaption">
         <div class="magnify">
          <a class="internal" href="/wiki/File:AAKH-1784.jpg" title="Enlarge">
          </a>
         </div>
         <a href="/wiki/Vienna_General_Hospital" title="Vienna General Hospital">
          Vienna General Hospital
         </a>
         in 1784.
         <a class="mw-redirect" href="/wiki/Semmelweis" title="Semmelweis">
          Semmelweis
         </a>
         worked at the maternity clinic. Copper engraving by Josef &amp; Peter Schafer
        </div>
       </div>
      </div>
      <p>
       Historically,
       <a class="mw-redirect" href="/wiki/Puerperal_fever" title="Puerperal fever">
        puerperal fever
       </a>
       was a devastating disease. It affected women within the first three days after
       <a href="/wiki/Childbirth" title="Childbirth">
        childbirth
       </a>
       and progressed rapidly, causing acute symptoms of severe abdominal pain,
       <a href="/wiki/Fever" title="Fever">
        fever
       </a>
       and
       <a href="/wiki/Debility_(medical)" title="Debility (medical)">
        debility
       </a>
       .
      </p>
      <p>
       The most common infection causing puerperal fever is genital tract
       <a href="/wiki/Sepsis" title="Sepsis">
        sepsis
       </a>
       caused by contaminated medical equipment or unhygienic medical staff who contaminate the mother's genital tract during the delivery. Other types of infection that can lead to sepsis after childbirth include
       <a href="/wiki/Urinary_tract_infection" title="Urinary tract infection">
        urinary tract infection
       </a>
       , breast infection (mastitis) and respiratory tract infection (more common after
       <a class="mw-redirect" href="/wiki/Anaesthesia" title="Anaesthesia">
        anaesthesia
       </a>
       due to lesions in the trachea). Puerperal fever is now rare in the West due to improved hygiene during delivery, and the few infections that do occur are usually treatable with
       <a href="/wiki/Antibiotics" title="Antibiotics">
        antibiotics
       </a>
       .
      </p>
      <p>
      </p>
      <div class="toc" id="toc">
       <div class="toctitle">
        <h2>
         Contents
        </h2>
       </div>
       <ul>
        <li class="toclevel-1 tocsection-1">
         <a href="#The_work_of_Dr._Ignaz_Semmelweis">
          <span class="tocnumber">
           1
          </span>
          <span class="toctext">
           The work of Dr. Ignaz Semmelweis
          </span>
         </a>
         <ul>
          <li class="toclevel-2 tocsection-2">
           <a href="#Puerperal_fever_.E2.80.93_a_modern_disease">
            <span class="tocnumber">
             1.1
            </span>
            <span class="toctext">
             Puerperal fever – a modern disease
            </span>
           </a>
          </li>
          <li class="toclevel-2 tocsection-3">
           <a href="#Hospital_H.C3.B4tel-Dieu_de_Paris">
            <span class="tocnumber">
             1.2
            </span>
            <span class="toctext">
             Hospital Hôtel-Dieu de Paris
            </span>
           </a>
          </li>
          <li class="toclevel-2 tocsection-4">
           <a href="#The_maternity_clinic_at_W.C3.BCrzburg">
            <span class="tocnumber">
             1.3
            </span>
            <span class="toctext">
             The maternity clinic at Würzburg
            </span>
           </a>
          </li>
          <li class="toclevel-2 tocsection-5">
           <a href="#Inconsistencies_in_data">
            <span class="tocnumber">
             1.4
            </span>
            <span class="toctext">
             Inconsistencies in data
            </span>
           </a>
          </li>
         </ul>
        </li>
        <li class="toclevel-1 tocsection-6">
         <a href="#Mortality_rates_at_the_Vienna_General_Hospital">
          <span class="tocnumber">
           2
          </span>
          <span class="toctext">
           Mortality rates at the Vienna General Hospital
          </span>
         </a>
         <ul>
          <li class="toclevel-2 tocsection-7">
           <a href="#Monthly_mortality_rates_for_birthgiving_women_1841.E2.80.931849">
            <span class="tocnumber">
             2.1
            </span>
            <span class="toctext">
             Monthly mortality rates for birthgiving women 1841–1849
            </span>
           </a>
          </li>
          <li class="toclevel-2 tocsection-8">
           <a href="#Explanatory_power_of_his_theory_of_cadaverous_poisoning">
            <span class="tocnumber">
             2.2
            </span>
            <span class="toctext">
             Explanatory power of his theory of cadaverous poisoning
            </span>
           </a>
          </li>
          <li class="toclevel-2 tocsection-9">
           <a href="#Yearly_mortality_rates_for_birthgiving_women_1833.E2.80.931858_for_first_and_second_clinics">
            <span class="tocnumber">
             2.3
            </span>
            <span class="toctext">
             Yearly mortality rates for birthgiving women 1833–1858 for first and second clinics
            </span>
           </a>
          </li>
          <li class="toclevel-2 tocsection-10">
           <a href="#Yearly_mortality_rates_for_birthgiving_women_1784.E2.80.931849">
            <span class="tocnumber">
             2.4
            </span>
            <span class="toctext">
             Yearly mortality rates for birthgiving women 1784–1849
            </span>
           </a>
          </li>
          <li class="toclevel-2 tocsection-11">
           <a href="#Yearly_mortality_rates_for_newborn_infants_1841-1846_for_first_and_second_clinics">
            <span class="tocnumber">
             2.5
            </span>
            <span class="toctext">
             Yearly mortality rates for newborn infants 1841-1846 for first and second clinics
            </span>
           </a>
          </li>
         </ul>
        </li>
        <li class="toclevel-1 tocsection-12">
         <a href="#Yearly_patient_mortality_rates_at_the_Dublin_Maternity_Hospital_1784-1849">
          <span class="tocnumber">
           3
          </span>
          <span class="toctext">
           Yearly patient mortality rates at the Dublin Maternity Hospital 1784-1849
          </span>
         </a>
        </li>
        <li class="toclevel-1 tocsection-13">
         <a href="#Contamination_of_midwives.27_hands">
          <span class="tocnumber">
           4
          </span>
          <span class="toctext">
           Contamination of midwives' hands
          </span>
         </a>
        </li>
        <li class="toclevel-1 tocsection-14">
         <a href="#References">
          <span class="tocnumber">
           5
          </span>
          <span class="toctext">
           References
          </span>
         </a>
         <ul>
          <li class="toclevel-2 tocsection-15">
           <a href="#Notes">
            <span class="tocnumber">
             5.1
            </span>
            <span class="toctext">
             Notes
            </span>
           </a>
          </li>
          <li class="toclevel-2 tocsection-16">
           <a href="#Books">
            <span class="tocnumber">
             5.2
            </span>
            <span class="toctext">
             Books
            </span>
           </a>
          </li>
         </ul>
        </li>
        <li class="toclevel-1 tocsection-17">
         <a href="#External_links">
          <span class="tocnumber">
           6
          </span>
          <span class="toctext">
           External links
          </span>
         </a>
        </li>
       </ul>
      </div>
      <p>
      </p>
      <h2>
       <span class="mw-headline" id="The_work_of_Dr._Ignaz_Semmelweis">
        The work of Dr. Ignaz Semmelweis
       </span>
       <span class="mw-editsection">
        <span class="mw-editsection-bracket">
         [
        </span>
        <a href="/w/index.php?title=Historical_mortality_rates_of_puerperal_fever&amp;action=edit&amp;section=1" title="Edit section: The work of Dr. Ignaz Semmelweis">
         edit
        </a>
        <span class="mw-editsection-bracket">
         ]
        </span>
       </span>
      </h2>
      <p>
       Dr.
       <a href="/wiki/Ignaz_Semmelweis" title="Ignaz Semmelweis">
        Ignaz Semmelweis
       </a>
       worked at the
       <a href="/wiki/Vienna_General_Hospital" title="Vienna General Hospital">
        Vienna General Hospital
       </a>
       's maternity clinic on a 3-year contract from 1846–1849. There, as elsewhere in European and North American hospitals,
       <a class="mw-redirect" href="/wiki/Puerperal_fever" title="Puerperal fever">
        puerperal fever
       </a>
       , or childbed fever, was rampant, sometimes climbing to 40 percent of admitted patients. He was disturbed by these mortality rates, and eventually developed a theory of infection, in which he theorized that decaying matter on the hands of doctors, who had recently conducted autopsies, was brought into contact with the genitals of birthgiving women during the medical examinations at the maternity clinic. He proposed a radical hand washing theory using chlorinated lime, now a known disinfectant.
      </p>
      <p>
       At the time however, the
       <a class="mw-redirect" href="/wiki/Germ_theory" title="Germ theory">
        germ theory
       </a>
       of infection had not been developed and Semmelweis' ideas ran contrary to key medical beliefs and practices. His ideas were rejected and ridiculed. Quite unusually, his contract was not renewed, effectively expelling him from the medical community in Vienna. He died as an outcast in a mental institution.
      </p>
      <h3>
       <span id="Puerperal_fever_–_a_modern_disease">
       </span>
       <span class="mw-headline" id="Puerperal_fever_.E2.80.93_a_modern_disease">
        Puerperal fever – a modern disease
       </span>
       <span class="mw-editsection">
        <span class="mw-editsection-bracket">
         [
        </span>
        <a href="/w/index.php?title=Historical_mortality_rates_of_puerperal_fever&amp;action=edit&amp;section=2" title="Edit section: Puerperal fever – a modern disease">
         edit
        </a>
        <span class="mw-editsection-bracket">
         ]
        </span>
       </span>
      </h3>
      <p>
       An 1841 account of epidemic childbed fever states that insofar as existing historical documents permit one to judge, childbed fever is a modern disease. The cases reported by
       <a href="/wiki/Hippocrates" title="Hippocrates">
        Hippocrates
       </a>
       that are generally identified as such are not puerperal fever. There are only examples of
       <a href="/wiki/Bilious_fever" title="Bilious fever">
        bilious fever
       </a>
       , then common, which among maternity patients was no different from its appearance among non-maternity patients or men; Hippocrates himself never identified it as a separate and distinguishable disease.
       <sup class="reference" id="cite_ref-Semmelweis_1861_p152_1-0">
        <a href="#cite_note-Semmelweis_1861_p152-1">
         [1]
        </a>
       </sup>
      </p>
      <h3>
       <span id="Hospital_Hôtel-Dieu_de_Paris">
       </span>

In [11]:
soup.table.tr.th.text

'Year'

In [9]:
#table_2 = soup.find_all('table')[1]#.tr.th.text

In [13]:
#columns = soup.table.tr.find_all('th')#[1].text

In [14]:
columns = soup.table.tr.find_all('th')#[1].text

column_names = []

for col in columns:
    column_names.append(col.text)

column_names

['Year', 'Month', 'Births', 'Deaths', 'Rate (%)', 'Notes']

In [15]:
rows = soup.table.find_all('tr')

table_rows = []
vector = []

for row in rows[1:]:
    data = row.find_all('td')
    vector = []
    for el in data:
        vector.append(el.text)
    table_rows.append(vector)

table_rows

[['1841', '000000001841-01-01-0000January 1841', '254', '37', '14.6', ''],
 ['\xa0', '000000001841-02-01-0000February 1841', '239', '18', '7.5', ''],
 ['\xa0', '000000001841-03-01-0000March 1841', '277', '12', '4.3', ''],
 ['\xa0', '000000001841-04-01-0000April 1841', '255', '4', '1.6', ''],
 ['\xa0', '000000001841-05-01-0000May 1841', '255', '2', '0.8', ''],
 ['\xa0', '000000001841-06-01-0000June 1841', '200', '10', '5.0', ''],
 ['\xa0', '000000001841-07-01-0000July 1841', '190', '16', '8.4'],
 ['\xa0', '000000001841-08-01-0000August 1841', '222', '3', '1.4'],
 ['\xa0', '000000001841-09-01-0000September 1841', '213', '4', '1.9'],
 ['\xa0', '000000001841-10-01-0000October 1841', '236', '26', '11.0'],
 ['\xa0', '000000001841-11-01-0000November 1841', '235', '53', '22.6'],
 ['\xa0', '000000001841-12-01-0000December 1841', 'na', 'na', 'na'],
 ['1842', '000000001842-01-01-0000January 1842', '307', '64', '20.8'],
 ['\xa0', '000000001842-02-01-0000February 1842', '311', '38', '12.2'],
 ['\xa0', '000000001842-03-01-0000March 1842', '264', '27', '10.2'],
 ['\xa0', '000000001842-04-01-0000April 1842', '242', '26', '10.7'],
 ['\xa0', '000000001842-05-01-0000May 1842', '310', '10', '3.2'],
 ['\xa0', '000000001842-06-01-0000June 1842', '273', '18', '6.6'],
 ['\xa0', '000000001842-07-01-0000July 1842', '231', '48', '20.8'],
 ['\xa0', '000000001842-08-01-0000August 1842', '216', '55', '25.5'],
 ['\xa0', '000000001842-09-01-0000September 1842', '223', '41', '18.4'],
 ['\xa0', '000000001842-10-01-0000October 1842', '242', '71', '29.3'],
 ['\xa0', '000000001842-11-01-0000November 1842', '209', '48', '23.0'],
 ['\xa0', '000000001842-12-01-0000December 1842', '239', '75', '31.4'],
 ['1843', 'Jan 1843', '272', '52', '19.1'],
 ['\xa0', 'Feb 1843', '263', '42', '16.0'],
 ['\xa0', 'Mar 1843', '266', '33', '12.4'],
 ['\xa0', 'Apr 1843', '285', '34', '11.9'],
 ['\xa0', 'May 1843', '246', '15', '6.1'],
 ['\xa0', 'June 1843', '196', '8', '4.1'],
 ['\xa0', 'July 1843', '191', '1', '0.5'],
 ['\xa0', 'August 1843', '193', '3', '1.6'],
 ['\xa0', 'Sep 1843', '221', '5', '2.3'],
 ['\xa0', 'Oct 1843', '250', '44', '17.6'],
 ['\xa0', 'November 1843', '252', '18', '7.1'],
 ['\xa0', 'December 1843', '236', '19', '8.1'],
 ['1844', 'Jan 1844', '244', '37', '15.2'],
 ['\xa0', 'Feb 1844', '257', '29', '11.3'],
 ['\xa0', 'Mar 1844', '276', '47', '17.0'],
 ['\xa0', 'Apr 1844', '208', '36', '17.3'],
 ['\xa0', 'Maj 1844', '240', '14', '5.8'],
 ['\xa0', 'Jun 1844', '224', '6', '2.7'],
 ['\xa0', 'Jul 1844', '206', '9', '4.4'],
 ['\xa0', 'Aug', '269', '17', '6.3'],
 ['\xa0', 'Sep', '245', '3', '1.2'],
 ['\xa0', 'Oct', '248', '8', '3.2'],
 ['\xa0', 'Nov', '245', '27', '11.0'],
 ['\xa0', 'Dec', '256', '27', '10.5'],
 ['1845', 'Jan', '303', '23', '7.6'],
 ['\xa0', 'Feb', '274', '13', '4.7'],
 ['\xa0', 'Mar', '292', '13', '4.5'],
 ['\xa0', 'Apr', '260', '11', '4.2'],
 ['\xa0', 'May', '296', '13', '4.4'],
 ['\xa0', 'Jun', '280', '20', '7.1'],
 ['\xa0', 'Jul', '245', '15', '6.1'],
 ['\xa0', 'Aug', '251', '9', '3.6'],
 ['\xa0', 'Sep', '237', '25', '10.5'],
 ['\xa0', 'Oct', '283', '42', '14.8'],
 ['\xa0', 'Nov', '265', '29', '10.9'],
 ['\xa0', 'Dec', '267', '28', '10.5'],
 ['1846', 'Jan 1846', '336', '45', '13.4'],
 ['\xa0', 'Feb', '293', '53', '18.1'],
 ['\xa0', 'Mar', '311', '48', '15.4'],
 ['\xa0', 'Apr', '253', '48', '19.0'],
 ['\xa0', 'May', '305', '41', '13.4'],
 ['\xa0', 'Jun 1846', '266', '27', '10.2'],
 ['\xa0', 'Jul 1846', '252', '33', '13.1'],
 ['\xa0', 'Aug', '216', '39', '18.1'],
 ['\xa0', 'Sep', '271', '39', '14.4'],
 ['\xa0', 'October 1846', '254', '38', '15.0'],
 ['\xa0', 'Nov', '297', '32', '10.8'],
 ['\xa0', 'Dec 1846', '298', '16', '5.4'],
 ['1847', 'Jan 1847', '311', '10', '3.2'],
 ['\xa0', 'Feb', '312', '6', '1.9'],
 ['\xa0', 'Mar 1847', '305', '11', '3.6'],
 ['\xa0', 'Apr 1847', '312', '57', '18.3'],
 ['\xa0', 'May', '294', '36', '12.2', 'Handwashing policy instituted mid-May'],
 ['\xa0', 'Jun 1847', '268', '6', '2.2'],
 ['\xa0', 'Jul', '250', '3', '1.2'],
 ['\xa0', 'Aug', '264', '5', '1.9'],
 ['\xa0', 'Sep', '262', '12', '4.6'],
 ['\xa0', 'Okt', '278', '11', '4.0'],
 ['\xa0', 'Nov', '246', '11', '4.5'],
 ['\xa0', 'Dec 1847', '273', '8', '2.9'],
 ['1848',
  'Jan 1848',
  '283',
  '10',
  '3.5',
  "strict controls enforced on students'\nnegligent hand-wash"],
 ['\xa0', 'Feb 1848', '291', '2', '0.7'],
 ['\xa0', 'March 1848', '276', '0', '0.0'],
 ['\xa0', 'April 1848', '305', '2', '0.7'],
 ['\xa0', 'May 1848', '313', '3', '1.0'],
 ['\xa0', 'Jun 1848', '264', '3', '1.1'],
 ['\xa0', 'Jul 1848', '269', '1', '0.4'],
 ['\xa0', 'Aug 1848', '261', '0', '0.0'],
 ['\xa0', 'Sep 1848', '312', '3', '1.0'],
 ['\xa0', 'Oct 1848', '299', '7', '2.3'],
 ['\xa0', 'Nov 1848', '310', '9', '2.9'],
 ['', 'Dec 1848', '373', '5', '1.3'],
 ['', 'Jan 1849', '403', '9', '2.2'],
 ['', 'Feb 1849', '389', '12', '3.1'],
 ['', 'Mar 1849', '406', '20', '4.9', "Semmelweis' employment terminated"]]

In [18]:
Data = pd.DataFrame(table_rows,columns=column_names)

In [19]:
Data

,Year,Month,Births,Deaths,Rate (%),Notes
0,1841,000000001841-01-01-0000January 1841,254,37,14.6,
1,,000000001841-02-01-0000February 1841,239,18,7.5,
2,,000000001841-03-01-0000March 1841,277,12,4.3,
3,,000000001841-04-01-0000April 1841,255,4,1.6,
4,,000000001841-05-01-0000May 1841,255,2,0.8,
5,,000000001841-06-01-0000June 1841,200,10,5.0,
6,,000000001841-07-01-0000July 1841,190,16,8.4,None
7,,000000001841-08-01-0000August 1841,222,3,1.4,None
8,,000000001841-09-01-0000September 1841,213,4,1.9,None
9,,000000001841-10-01-0000October 1841,236,26,11.0,None
10,,000000001841-11-01-0000November 1841,235,53,22.6,None
11,,000000001841-12-01-0000December 1841,na,na,na,None
12,1842,000000001842-01-01-0000January 1842,307,64,20.8,None
13,,000000001842-02-01-0000February 1842,311,38,12.2,None
14,,000000001842-03-01-0000March 1842,264,27,10.2,None
15,,000000001842-04-01-0000April 1842,242,26,10.7,None
16,,000000001842-05-01-0000May 1842,310,10,3.2,None
17,,000000001842-06-01-0000June 1842,273,18,6.6,None
18,,000000001842-07-01-0000July 1842,231,48,20.8,None
19,,000000001842-08-01-0000August 1842,216,55,25.5,None
20,,000000001842-09-01-0000September 1842,223,41,18.4,None
21,,000000001842-10-01-0000October 1842,242,71,29.3,None
22,,000000001842-11-01-0000November 1842,209,48,23.0,None
23,,000000001842-12-01-0000December 1842,239,75,31.4,None
24,1843,Jan 1843,272,52,19.1,None
25,,Feb 1843,263,42,16.0,None
26,,Mar 1843,266,33,12.4,None
27,,Apr 1843,285,34,11.9,None
28,,May 1843,246,15,6.1,None
29,,June 1843,196,8,4.1,None
...,...,...,...,...,...,...
69,,October 1846,254,38,15.0,None
70,,Nov,297,32,10.8,None
71,,Dec 1846,298,16,5.4,None
72,1847,Jan 1847,311,10,3.2,None
73,,Feb,312,6,1.9,None
74,,Mar 1847,305,11,3.6,None
75,,Apr 1847,312,57,18.3,None
76,,May,294,36,12.2,Handwashing policy instituted mid-May
77,,Jun 1847,268,6,2.2,None
78,,Jul,250,3,1.2,None
79,,Aug,264,5,1.9,None
80,,Sep,262,12,4.6,None
81,,Okt,278,11,4.0,None
82,,Nov,246,11,4.5,None
83,,Dec 1847,273,8,2.9,None
84,1848,Jan 1848,283,10,3.5,strict controls enforced on students'\nneglige...
85,,Feb 1848,291,2,0.7,None
86,,March 1848,276,0,0.0,None
87,,April 1848,305,2,0.7,None
88,,May 1848,313,3,1.0,None
89,,Jun 1848,264,3,1.1,None
90,,Jul 1848,269,1,0.4,None
91,,Aug 1848,261,0,0.0,None
92,,Sep 1848,312,3,1.0,None
93,,Oct 1848,299,7,2.3,None
94,,Nov 1848,310,9,2.9,None
95,,Dec 1848,373,5,1.3,None
96,,Jan 1849,403,9,2.2,None
97,,Feb 1849,389,12,3.1,None
98,,Mar 1849,406,20,4.9,Semmelweis' employment terminated

In [46]:
Data.Year = Data.Month.apply(lambda x: x[-4:]).replace(regex={'\D+': np.nan}).fillna(method='ffill')

In [57]:
Data.Month = Data.Month.str.extract('([a-zA-Z]{3})\.*', expand=False)

In [90]:
Data = Data.replace('na',0).fillna('')

In [91]:
Data

,Year,Month,Births,Deaths,Rate (%),Notes
0,1841,Jan,254,37,14.6,
1,1841,Feb,239,18,7.5,
2,1841,Mar,277,12,4.3,
3,1841,Apr,255,4,1.6,
4,1841,May,255,2,0.8,
5,1841,Jun,200,10,5.0,
6,1841,Jul,190,16,8.4,
7,1841,Aug,222,3,1.4,
8,1841,Sep,213,4,1.9,
9,1841,Oct,236,26,11.0,
10,1841,Nov,235,53,22.6,
11,1841,Dec,0,0,0,
12,1842,Jan,307,64,20.8,
13,1842,Feb,311,38,12.2,
14,1842,Mar,264,27,10.2,
15,1842,Apr,242,26,10.7,
16,1842,May,310,10,3.2,
17,1842,Jun,273,18,6.6,
18,1842,Jul,231,48,20.8,
19,1842,Aug,216,55,25.5,
20,1842,Sep,223,41,18.4,
21,1842,Oct,242,71,29.3,
22,1842,Nov,209,48,23.0,
23,1842,Dec,239,75,31.4,
24,1843,Jan,272,52,19.1,
25,1843,Feb,263,42,16.0,
26,1843,Mar,266,33,12.4,
27,1843,Apr,285,34,11.9,
28,1843,May,246,15,6.1,
29,1843,Jun,196,8,4.1,
...,...,...,...,...,...,...
69,1846,Oct,254,38,15.0,
70,1846,Nov,297,32,10.8,
71,1846,Dec,298,16,5.4,
72,1847,Jan,311,10,3.2,
73,1847,Feb,312,6,1.9,
74,1847,Mar,305,11,3.6,
75,1847,Apr,312,57,18.3,
76,1847,May,294,36,12.2,Handwashing policy instituted mid-May
77,1847,Jun,268,6,2.2,
78,1847,Jul,250,3,1.2,
79,1847,Aug,264,5,1.9,
80,1847,Sep,262,12,4.6,
81,1847,Okt,278,11,4.0,
82,1847,Nov,246,11,4.5,
83,1847,Dec,273,8,2.9,
84,1848,Jan,283,10,3.5,strict controls enforced on students'\nneglige...
85,1848,Feb,291,2,0.7,
86,1848,Mar,276,0,0.0,
87,1848,Apr,305,2,0.7,
88,1848,May,313,3,1.0,
89,1848,Jun,264,3,1.1,
90,1848,Jul,269,1,0.4,
91,1848,Aug,261,0,0.0,
92,1848,Sep,312,3,1.0,
93,1848,Oct,299,7,2.3,
94,1848,Nov,310,9,2.9,
95,1848,Dec,373,5,1.3,
96,1849,Jan,403,9,2.2,
97,1849,Feb,389,12,3.1,
98,1849,Mar,406,20,4.9,Semmelweis' employment terminated

In [93]:
Data.to_csv('data/hand_wash.csv')

In [10]:
table_2 = soup.find_all('table')[1]#.tr.th.text

In [25]:
columns_2 = table_2.find_all('tr')[1].find_all('th')#[1].text

column_names_2 = []

for col in columns_2:
    column_names_2.append(col.text)

column_names_2.insert(4,'')
column_names_2

['Year',
 'Births',
 'Deaths',
 'Rate (%)',
 '',
 'Births',
 'Deaths',
 'Rate (%)',
 'Note']

In [12]:
rows_2 = table_2.find_all('tr')

table_rows_2 = []
vector_2 = []

for row in rows_2:
    data_2 = row.find_all('td')
    vector_2 = []
    for el in data_2:
        vector_2.append(el.text)
    table_rows_2.append(vector_2)

table_rows_2

[[''],
 ['\xa0'],
 ['1833',
  '3,737',
  '197',
  '5.3',
  '\xa0',
  '353',
  '8',
  '2.3',
  'Second clinic started'],
 ['1834', '2,657', '205', '7.7', '\xa0', '1,744', '150', '8.6'],
 ['1835', '2,573', '143', '5.6', '\xa0', '1,682', '84', '5.0'],
 ['1836', '2,677', '200', '7.5', '\xa0', '1,670', '131', '7.8'],
 ['1837', '2,765', '251', '9.1', '\xa0', '1,784', '124', '7.0'],
 ['1838', '2,987', '91', '3.0', '\xa0', '1,779', '88', '4.9'],
 ['1839', '2,781', '151', '5.4', '\xa0', '2,010', '91', '4.5'],
 ['1840', '2,889', '267', '9.2', '\xa0', '2,073', '55', '2.7'],
 ['1841',
  '3,036',
  '237',
  '7.8',
  '\xa0',
  '2,442',
  '86',
  '3.5',
  'Only midwives worked in the second clinic'],
 ['1842', '3,287', '518', '15.8', '\xa0', '2,659', '202', '7.6'],
 ['1843', '3,060', '274', '9.0', '\xa0', '2,739', '164', '6.0'],
 ['1844', '3,157', '260', '8.2', '\xa0', '2,956', '68', '2.3'],
 ['1845', '3,492', '241', '6.9', '\xa0', '3,241', '66', '2.0'],
 ['1846', '4,010', '459', '11.4', '\xa0', '3,754', '105', '2.8'],
 ['1847',
  '3,490',
  '176',
  '5.0',
  '\xa0',
  '3,306',
  '32',
  '1.0',
  'Handwashing in first clinic mid-May'],
 ['1848', '3,556', '45', '1.3', '\xa0', '3,319', '43', '1.3'],
 ['1849',
  '3,858',
  '103',
  '2.7',
  '\xa0',
  '3,371',
  '87',
  '2.6',
  'Semmelweis dismissed in March'],
 ['1850', '3,745', '74', '2.0', '\xa0', '3,261', '54', '1.7'],
 ['1851', '4,194', '75', '1.8', '\xa0', '3,395', '121', '3.6'],
 ['1852', '4,471', '181', '4.0', '\xa0', '3,360', '192', '5.7'],
 ['1853', '4,221', '94', '2.2', '\xa0', '3,480', '67', '1.9'],
 ['1854', '4,393', '400', '9.1', '\xa0', '3,396', '210', '6.2'],
 ['1855', '3,659', '198', '5.4', '\xa0', '2,938', '174', '5.9'],
 ['1856', '3,925', '156', '4.0', '\xa0', '3,070', '125', '4.1'],
 ['1857', '4,220', '124', '2.9', '\xa0', '3,795', '83', '2.2'],
 ['1858', '4,203', '86', '2.0', '\xa0', '4,179', '60', '1.4']]

In [56]:
Data_2 = pd.DataFrame(table_rows_2[2:],columns=column_names_2)
Data_2 = Data_2.replace('na',0).fillna('')

In [57]:
Data_2

,Year,Births,Deaths,Rate (%),,Births,Deaths,Rate (%),Note
0,1833,"3,737",197,5.3,,353,8,2.3,Second clinic started
1,1834,"2,657",205,7.7,,"1,744",150,8.6,
2,1835,"2,573",143,5.6,,"1,682",84,5.0,
3,1836,"2,677",200,7.5,,"1,670",131,7.8,
4,1837,"2,765",251,9.1,,"1,784",124,7.0,
5,1838,"2,987",91,3.0,,"1,779",88,4.9,
6,1839,"2,781",151,5.4,,"2,010",91,4.5,
7,1840,"2,889",267,9.2,,"2,073",55,2.7,
8,1841,"3,036",237,7.8,,"2,442",86,3.5,Only midwives worked in the second clinic
9,1842,"3,287",518,15.8,,"2,659",202,7.6,
10,1843,"3,060",274,9.0,,"2,739",164,6.0,
11,1844,"3,157",260,8.2,,"2,956",68,2.3,
12,1845,"3,492",241,6.9,,"3,241",66,2.0,
13,1846,"4,010",459,11.4,,"3,754",105,2.8,
14,1847,"3,490",176,5.0,,"3,306",32,1.0,Handwashing in first clinic mid-May
15,1848,"3,556",45,1.3,,"3,319",43,1.3,
16,1849,"3,858",103,2.7,,"3,371",87,2.6,Semmelweis dismissed in March
17,1850,"3,745",74,2.0,,"3,261",54,1.7,
18,1851,"4,194",75,1.8,,"3,395",121,3.6,
19,1852,"4,471",181,4.0,,"3,360",192,5.7,
20,1853,"4,221",94,2.2,,"3,480",67,1.9,
21,1854,"4,393",400,9.1,,"3,396",210,6.2,
22,1855,"3,659",198,5.4,,"2,938",174,5.9,
23,1856,"3,925",156,4.0,,"3,070",125,4.1,
24,1857,"4,220",124,2.9,,"3,795",83,2.2,
25,1858,"4,203",86,2.0,,"4,179",60,1.4,

In [33]:
Data_2.to_csv('data/clinic_compare.csv')

In [35]:
table_3 = soup.find_all('table')[2]#.tr.th.text

In [51]:
columns_3 = table_3.find_all('tr')[0].find_all('td')#[1].text

column_names_3 = []

for col in columns_3:
    column_names_3.append(col.text)

column_names_3#.insert(4,'')
#column_names_3

['Year', 'Births', 'Deaths', 'Rate (%)', 'Note']

In [50]:
table_3.find_all('tr')[0]

<tr align="right" valign="bottom">
<td height="13" width="48">Year</td>
<td width="49">Births</td>
<td width="49">Deaths</td>
<td width="48">Rate (%)</td>
<td>Note</td>
</tr>

In [41]:
columns_3

[<tr align="right" valign="bottom">
 <td height="13" width="48">Year</td>
 <td width="49">Births</td>
 <td width="49">Deaths</td>
 <td width="48">Rate (%)</td>
 <td>Note</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1784</td>
 <td>284</td>
 <td>6</td>
 <td>2.1</td>
 <td>No <a class="mw-redirect" href="/wiki/Pathological_anatomy" title="Pathological anatomy">pathological anatomy</a></td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1785</td>
 <td>899</td>
 <td>13</td>
 <td>1.4</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1786</td>
 <td>1,151</td>
 <td>5</td>
 <td>0.4</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1787</td>
 <td>1,407</td>
 <td>5</td>
 <td>0.4</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1788</td>
 <td>1,425</td>
 <td>5</td>
 <td>0.4</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1789</td>
 <td>1,246</td>
 <td>7</td>
 <td>0.6</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1790</td>
 <td>1,326</td>
 <td>10</td>
 <td>0.8</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1791</td>
 <td>1,395</td>
 <td>8</td>
 <td>0.6</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1792</td>
 <td>1,579</td>
 <td>14</td>
 <td>0.9</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1793</td>
 <td>1,684</td>
 <td>44</td>
 <td>2.6</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1794</td>
 <td>1,768</td>
 <td>7</td>
 <td>0.4</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1795</td>
 <td>1,798</td>
 <td>38</td>
 <td>2.1</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1796</td>
 <td>1,904</td>
 <td>22</td>
 <td>1.2</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1797</td>
 <td>2,012</td>
 <td>5</td>
 <td>0.2</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1798</td>
 <td>2,046</td>
 <td>5</td>
 <td>0.2</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1799</td>
 <td>2,067</td>
 <td>20</td>
 <td>1.0</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1800</td>
 <td>2,070</td>
 <td>41</td>
 <td>2.0</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1801</td>
 <td>2,106</td>
 <td>17</td>
 <td>0.8</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1802</td>
 <td>2,346</td>
 <td>9</td>
 <td>0.4</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1803</td>
 <td>2,215</td>
 <td>16</td>
 <td>0.7</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1804</td>
 <td>2,022</td>
 <td>8</td>
 <td>0.4</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1805</td>
 <td>2,112</td>
 <td>9</td>
 <td>0.4</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1806</td>
 <td>1,875</td>
 <td>13</td>
 <td>0.7</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1807</td>
 <td>925</td>
 <td>6</td>
 <td>0.6</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1808</td>
 <td>855</td>
 <td>7</td>
 <td>0.8</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1809</td>
 <td>912</td>
 <td>13</td>
 <td>1.4</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1810</td>
 <td>744</td>
 <td>6</td>
 <td>0.8</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1811</td>
 <td>1,050</td>
 <td>20</td>
 <td>1.9</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1812</td>
 <td>1,419</td>
 <td>9</td>
 <td>0.6</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1813</td>
 <td>1,945</td>
 <td>21</td>
 <td>1.1</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1814</td>
 <td>2,062</td>
 <td>66</td>
 <td>3.2</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1815</td>
 <td>2,591</td>
 <td>19</td>
 <td>0.7</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1816</td>
 <td>2,410</td>
 <td>12</td>
 <td>0.5</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1817</td>
 <td>2,735</td>
 <td>25</td>
 <td>0.9</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1818</td>
 <td>2,568</td>
 <td>56</td>
 <td>2.2</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1819</td>
 <td>3,089</td>
 <td>154</td>
 <td>5.0</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1820</td>
 <td>2,998</td>
 <td>75</td>
 <td>2.5</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1821</td>
 <td>3,294</td>
 <td>55</td>
 <td>1.7</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1822</td>
 <td>3,066</td>
 <td>26</td>
 <td>0.8</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1823</td>
 <td>2,872</td>
 <td>214</td>
 <td>7.5</td>
 <td><a class="mw-redirect" href="/wiki/Pathological_anatomy" title="Pathological anatomy">Pathological anatomy</a> begins</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1824</td>
 <td>2,911</td>
 <td>144</td>
 <td>4.9</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1825</td>
 <td>2,594</td>
 <td>229</td>
 <td>8.8</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1826</td>
 <td>2,359</td>
 <td>192</td>
 <td>8.1</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1827</td>
 <td>2,367</td>
 <td>51</td>
 <td>2.2</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1828</td>
 <td>2,833</td>
 <td>101</td>
 <td>3.6</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1829</td>
 <td>3,012</td>
 <td>140</td>
 <td>4.6</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1830</td>
 <td>2,797</td>
 <td>111</td>
 <td>4.0</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1831</td>
 <td>3,353</td>
 <td>222</td>
 <td>6.6</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1832</td>
 <td>3,331</td>
 <td>105</td>
 <td>3.2</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1833</td>
 <td>3,737</td>
 <td>197</td>
 <td>5.3</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1834</td>
 <td>2,657</td>
 <td>205</td>
 <td>7.7</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1835</td>
 <td>2,573</td>
 <td>143</td>
 <td>5.6</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1836</td>
 <td>2,677</td>
 <td>200</td>
 <td>7.5</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1837</td>
 <td>2,765</td>
 <td>251</td>
 <td>9.1</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1838</td>
 <td>2,987</td>
 <td>91</td>
 <td>3.0</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1839</td>
 <td>2,781</td>
 <td>151</td>
 <td>5.4</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1840</td>
 <td>2,889</td>
 <td>267</td>
 <td>9.2</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1841</td>
 <td>3,036</td>
 <td>237</td>
 <td>7.8</td>
 <td>Separation of clinics</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1842</td>
 <td>3,287</td>
 <td>518</td>
 <td>15.8</td>
 <td>hereafter numbers refer to first clinic only</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1843</td>
 <td>3,060</td>
 <td>274</td>
 <td>9.0</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1844</td>
 <td>3,157</td>
 <td>260</td>
 <td>8.2</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1845</td>
 <td>3,492</td>
 <td>241</td>
 <td>6.9</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1846</td>
 <td>4,010</td>
 <td>459</td>
 <td>11.4</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1847</td>
 <td>3,490</td>
 <td>176</td>
 <td>5.0</td>
 <td>Chlorine washings begin mid-May</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1848</td>
 <td>3,556</td>
 <td>45</td>
 <td>1.3</td>
 </tr>, <tr align="right" valign="bottom">
 <td height="13">1849</td>
 <td>3,858</td>
 <td>103</td>
 <td>2.7</td>
 <td><a class="mw-redirect" href="/wiki/Semmelweis" title="Semmelweis">Semmelweis</a> dismissed from hospital in March</td>
 </tr>]

In [53]:
rows_3 = table_3.find_all('tr')

table_rows_3 = []
vector_3 = []

for row in rows_3[1:]:
    data_3 = row.find_all('td')
    vector_3 = []
    for el in data_3:
        vector_3.append(el.text)
    table_rows_3.append(vector_3)

table_rows_3

[['1784', '284', '6', '2.1', 'No pathological anatomy'],
 ['1785', '899', '13', '1.4'],
 ['1786', '1,151', '5', '0.4'],
 ['1787', '1,407', '5', '0.4'],
 ['1788', '1,425', '5', '0.4'],
 ['1789', '1,246', '7', '0.6'],
 ['1790', '1,326', '10', '0.8'],
 ['1791', '1,395', '8', '0.6'],
 ['1792', '1,579', '14', '0.9'],
 ['1793', '1,684', '44', '2.6'],
 ['1794', '1,768', '7', '0.4'],
 ['1795', '1,798', '38', '2.1'],
 ['1796', '1,904', '22', '1.2'],
 ['1797', '2,012', '5', '0.2'],
 ['1798', '2,046', '5', '0.2'],
 ['1799', '2,067', '20', '1.0'],
 ['1800', '2,070', '41', '2.0'],
 ['1801', '2,106', '17', '0.8'],
 ['1802', '2,346', '9', '0.4'],
 ['1803', '2,215', '16', '0.7'],
 ['1804', '2,022', '8', '0.4'],
 ['1805', '2,112', '9', '0.4'],
 ['1806', '1,875', '13', '0.7'],
 ['1807', '925', '6', '0.6'],
 ['1808', '855', '7', '0.8'],
 ['1809', '912', '13', '1.4'],
 ['1810', '744', '6', '0.8'],
 ['1811', '1,050', '20', '1.9'],
 ['1812', '1,419', '9', '0.6'],
 ['1813', '1,945', '21', '1.1'],
 ['1814', '2,062', '66', '3.2'],
 ['1815', '2,591', '19', '0.7'],
 ['1816', '2,410', '12', '0.5'],
 ['1817', '2,735', '25', '0.9'],
 ['1818', '2,568', '56', '2.2'],
 ['1819', '3,089', '154', '5.0'],
 ['1820', '2,998', '75', '2.5'],
 ['1821', '3,294', '55', '1.7'],
 ['1822', '3,066', '26', '0.8'],
 ['1823', '2,872', '214', '7.5', 'Pathological anatomy begins'],
 ['1824', '2,911', '144', '4.9'],
 ['1825', '2,594', '229', '8.8'],
 ['1826', '2,359', '192', '8.1'],
 ['1827', '2,367', '51', '2.2'],
 ['1828', '2,833', '101', '3.6'],
 ['1829', '3,012', '140', '4.6'],
 ['1830', '2,797', '111', '4.0'],
 ['1831', '3,353', '222', '6.6'],
 ['1832', '3,331', '105', '3.2'],
 ['1833', '3,737', '197', '5.3'],
 ['1834', '2,657', '205', '7.7'],
 ['1835', '2,573', '143', '5.6'],
 ['1836', '2,677', '200', '7.5'],
 ['1837', '2,765', '251', '9.1'],
 ['1838', '2,987', '91', '3.0'],
 ['1839', '2,781', '151', '5.4'],
 ['1840', '2,889', '267', '9.2'],
 ['1841', '3,036', '237', '7.8', 'Separation of clinics'],
 ['1842',
  '3,287',
  '518',
  '15.8',
  'hereafter numbers refer to first clinic only'],
 ['1843', '3,060', '274', '9.0'],
 ['1844', '3,157', '260', '8.2'],
 ['1845', '3,492', '241', '6.9'],
 ['1846', '4,010', '459', '11.4'],
 ['1847', '3,490', '176', '5.0', 'Chlorine washings begin mid-May'],
 ['1848', '3,556', '45', '1.3'],
 ['1849',
  '3,858',
  '103',
  '2.7',
  'Semmelweis dismissed from hospital in March']]

In [59]:
Data_3 = pd.DataFrame(table_rows_3,columns=column_names_3)
Data_3 = Data_3.replace('na',0).fillna('')

In [60]:
Data_3

    Year Births Deaths Rate (%)                                          Note
0   1784    284      6      2.1                       No pathological anatomy
1   1785    899     13      1.4
2   1786  1,151      5      0.4
3   1787  1,407      5      0.4
4   1788  1,425      5      0.4
5   1789  1,246      7      0.6
6   1790  1,326     10      0.8
7   1791  1,395      8      0.6
8   1792  1,579     14      0.9
9   1793  1,684     44      2.6
10  1794  1,768      7      0.4
11  1795  1,798     38      2.1
12  1796  1,904     22      1.2
13  1797  2,012      5      0.2
14  1798  2,046      5      0.2
15  1799  2,067     20      1.0
16  1800  2,070     41      2.0
17  1801  2,106     17      0.8
18  1802  2,346      9      0.4
19  1803  2,215     16      0.7
20  1804  2,022      8      0.4
21  1805  2,112      9      0.4
22  1806  1,875     13      0.7
23  1807    925      6      0.6
24  1808    855      7      0.8
25  1809    912     13      1.4
26  1810    744      6      0.8
27  1811  1,050     20      1.9
28  1812  1,419      9      0.6
29  1813  1,945     21      1.1
..   ...    ...    ...      ...                                           ...
36  1820  2,998     75      2.5
37  1821  3,294     55      1.7
38  1822  3,066     26      0.8
39  1823  2,872    214      7.5                   Pathological anatomy begins
40  1824  2,911    144      4.9
41  1825  2,594    229      8.8
42  1826  2,359    192      8.1
43  1827  2,367     51      2.2
44  1828  2,833    101      3.6
45  1829  3,012    140      4.6
46  1830  2,797    111      4.0
47  1831  3,353    222      6.6
48  1832  3,331    105      3.2
49  1833  3,737    197      5.3
50  1834  2,657    205      7.7
51  1835  2,573    143      5.6
52  1836  2,677    200      7.5
53  1837  2,765    251      9.1
54  1838  2,987     91      3.0
55  1839  2,781    151      5.4
56  1840  2,889    267      9.2
57  1841  3,036    237      7.8                         Separation of clinics
58  1842  3,287    518     15.8  hereafter numbers refer to first clinic only
59  1843  3,060    274      9.0
60  1844  3,157    260      8.2
61  1845  3,492    241      6.9
62  1846  4,010    459     11.4
63  1847  3,490    176      5.0               Chlorine washings begin mid-May
64  1848  3,556     45      1.3
65  1849  3,858    103      2.7   Semmelweis dismissed from hospital in March

[66 rows x 5 columns]